### ISSUE TITLE
Subscribe for email notification if more free places were added to a course

### ISSUE THREAD

**Issue by DanShepherd27** [solymosi/npu#44] opened 2020-06-12 12:17 UTC
It is quite frustrating when a course gets full, so when the study department adds some free places, you don't want to miss it. It would be great to have a feature where you do not have to check the course frequently, but rather get a notification about the newly added free places.
Is is possible to implement into the npu project?

HU: Feliratkozás kurzus-férőhely kibővítésről szóló értesítésre
Elég zavaró tud lenni, ha tárgyfelvételkor egy kurzus betelik, ezért amikor előfordul, hogy utólag a tanulmányi osztály kibővíti a férőhelyeket, nem kéne lekésni. Nagy segítség lenne, ha nem kellene rendszeresen nézegetni a neptunt, hanem emailben értesítene a kurzus kibővítéséről. Ez vajon megvalósítható az npu-n keresztül?

**Comment by Kokan** [comment] 2020-06-12 13:14
The npu runs on your machine that means it only runs if you have Neptun opened in your browser.
The bear minimum for such feature would be you to always have Neptun openned somewhere. (In which case a notification would be better suitable), or do some kind of service that does the always opening Neptun on your behalf (I think the later is out of scope of npu.).
But the biggest issue with this, this feature would still be limited by the ability that you can actually log in (and the server is not full with users).

Disclaimer:I am not the developper of npu, so the above is just from technical challenges that probably make this request infeasible.

**Comment by DanShepherd27** [comment] 2020-06-12 14:46
Yeah, you're probably right about that. Maybe someday universities will use a more advanced version of Neptun or a completely new service.

**Closed as completed** 2020-06-12 14:47 UTC
Labels: enhancement

**Comment by solymosi** [comment] 2020-06-12 17:57
This has been raised several times before. While such a feature would be awesome, there are a number of issues that make it very impractical to implement:

#### A server-side component would not work

As @Kokan mentioned, unless there was some kind of server side component that does the periodic checking, this would only work as long as Neptun is open in the browser. And even if such a component could be implemented, it would need to be hosted somewhere which incurs costs.

Then, users would have to trust whoever is maintaining this service with their Neptun password (otherwise the service couldn't log in in their name), and also trust that they secured the system properly so those passwords don't get hacked.

Having a single service checking everyone's courses also means that we'd have all these requests coming from a single IP which would get banned in no time by Neptun admins.

Because of all this, implementing a service like this makes little sense.

#### Things aren't much better on the client side either

Okay, so how about an extension to the current script that runs in the browser? Periodic checks while Neptun is open in the browser still make sense, right?

Wrong. The problem is in the numbers: if a lot of people started using this feature at the same time, that would put so much additional load on the Neptun servers that we would certainly see a reaction from universities. Today, Neptun PowerUp! is "tolerated" at most universities because 1) it has been designed not to significantly increase the load on the Neptun servers, and 2) they have no other choice since it is hard to definitively prove whether a request came from the script or from an actual user action.

Adding such a disruptive feature would change this status quo and would probably result in the script being banned in most if not all universities. Plus, since your browser would then be constantly making requests to Neptun, you would get identified as a Neptun PowerUp! user right away, which could lead to... negative consequences.

Even if we added in a very conservative timer &ndash; say, a check every 5 or 10 minutes &ndash; since the script is open source, anyone could change that to something like "once every second" in their own browser, initiating a "race to the bottom" where in the end everyone's constantly spamming the Neptun servers with requests, but exactly because of that nobody has a better chance of snatching up a place than before, not even with the script. Sounds like a lose-lose to me.

And I haven't even mentioned the **huge difficulties** involved in implementing this in the first place &ndash; it would be very difficult to make this feature work reliably. Also, if the feature malfunctions (i.e. never notifies you), that would be _worse_ than not having the feature at all, since without it you would at least remember to check your courses regularly.

**Comment by whisperity** [comment] 2020-07-13 09:52
> Adding such a disruptive feature would change this status quo and would probably result in the script being banned in most if not all universities. Plus, since your browser would then be constantly making requests to Neptun, you would get identified as a Neptun PowerUp! user right away, which could lead to... negative consequences.

I think the usage of this script is already in somewhat of a grey area. I would not say it's directly unlawful, but I have bits of hearsay which indicated that people **were** dragged in front of disciplinary committies ("fegyelmi bizottság") from using scripts to get a biased advantage against other students by "cheating the system".
Whether such script in question was NPU, or some other homebrew magic, I do not know...


> Yeah, you're probably right about that. Maybe someday universities will use a more advanced version of Neptun or a completely new service.

This is highly unlikely.

**Comment by solymosi** [comment] 2020-07-13 10:43
> I would not say it's directly unlawful, but I have bits of hearsay which indicated that people were dragged in front of disciplinary committies ("fegyelmi bizottság") from using scripts to get a biased advantage against other students by "cheating the system".

I know of [one instance](https://neptun.uni-obuda.hu/system/files/fegyelmi-hatarozat-2011-02-25.pdf) where someone got suspended for one semester for _authoring_ a similar script. I don't know of any instances where mere _users_ of such scripts faced any negative consequences.

This is why I used to publish the script under an alias while I was still studying in Hungary. A disciplinary hearing is not a proper legal procedure: if they want to can you for something, they don't have to prove that you broke a specific law or even just a specific internal regulation; "violating the code of ethics of the university" works just as nicely 😕

**Comment by whisperity** [comment] 2020-07-13 11:14
Wow, at ÓE they are publishing the disciplinary actions, meanwhile, I have to literally phone random numbers to find Faculty Council decisions on stuff, or know the right people. 😠

Ah yes, I think I remember the same case. The culprit is the "automated and recurring login" thing. NPU **is** guilty of the same thing. Luckily at ELTE you don't have to log in to the system on time, because subject registration is done by a freaky "let's sort people by magic random numbers" sort of thing, and exam registration is a moot point because they announce exam times way after the registration period has started...

Even the Dean calls me *Whisperity*.
I should be scared...

**Comment by solymosi** [comment] 2020-07-13 11:23
> Luckily at ELTE you don't have to log in to the system on time, because subject registration is done by a freaky "let's sort people by magic random numbers" sort of thing

...and something like that is the _real_ solution to overloaded Neptun servers. At the Swiss university I went to they have [an auction system](https://www.unisg.ch/en/wissen/begriff-des-monats/bidding) where everyone gets 1000 points and can use those to bid on courses. This results in the courses going to the students who want them the most and it also prevents people from signing up to too many courses in a single semester (there is a minimum bid). There are of course multiple rounds of bidding so if you make a mistake you can still for the most part correct it in later rounds.
